const GET_QUIZZES = 'GET_QUIZZES';
const GET_RESULTS = 'GET_RESULTS';
const UPDATE_STORIES = 'UPDATE_STORIES';
const SET_INDEX = 'SET_INDEX';
const NEXT_INDEX = 'NEXT_INDEX';
const PREVIOUS_INDEX = 'PREVIOUS_INDEX';
const RESET = 'RESET';
const UPDATE_ANSWERED = 'UPDATE_ANSWERED';
const NEXT_UNANSWERED = 'NEXT_UNANSWERED';
const FINISH = 'FINISH';
const ANSWERED = 'ANSWERED';
const IDLE = 'IDLE';
export {
    GET_QUIZZES,
    GET_RESULTS,
    UPDATE_STORIES,
    SET_INDEX,
    RESET,
    UPDATE_ANSWERED,
    NEXT_UNANSWERED,
    FINISH,
    IDLE,
    ANSWERED,
    NEXT_INDEX,
    PREVIOUS_INDEX
}



